### ISSUE TITLE
Configure using LocalConfiguration

### ISSUE THREAD

**Issue by Nemo64** [IchHabRecht/filefill#1]
I would like to be able to use the LocalConfiguration to configure file fill instead of the database. The reason is: I would like to have filefill as a dev dependency. But If I don't have filefill in production, then the configuration isn't in the production database and if I import the database than I loose my configuration.

**Comment by IchHabRecht** [comment]
Hi @Nemo64,

Thank you for your suggestion. I added the possibility to configure a storage using TYPO3_CONF_VARS in the associated pull request. Still some documentation is missing. 

If you want to give it a try, here is how you need to configure a storage:

```php
    // Given a file storage with uid 1
    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']['storages'][1] = [
        'domain' => 'https://example.com',
        'sys_domain' => true,
        'placeholder' => true,
    ];
```

Let me know what you think of this approach and if it solves your problem.

**Comment by Nemo64** [comment]
That is **exactly** what I want. You are awesome. I'll test it as soon as I have time.
