### ISSUE TITLE
Featurerequest: variables like image height / extension / width for URL

### ISSUE THREAD

**Issue by Fjonan** [IchHabRecht/filefill#12]
Ccustom syntax that allows to put image variables like extension, height and width into an single domain so URLs like this can be created: https://placekitten.com/%width%/%height%

**Comment by IchHabRecht** [comment]
Hi @Fjonan,

Thank you for your request. I think your proposal won't solve your real problem. By using an url with some special placeholders, you won't be able to properly handle necessary file extensions (e.g. only process images). What I will introduce is a new way of register resource handlers. You can find first work in https://github.com/IchHabRecht/filefill/tree/configure-resource-handler You will be able to register your own resource handler and add/use it in your sys_file_storage or TYPO3_CONF_VARS configuration.

**Comment by IchHabRecht** [comment]
Hi @Fjonan,

As I released a new version of filefill with the mentioned feature yesterday, I close this ticket right now. Thanks for your request and have fun with the new version.
