### ISSUE TITLE
Upload of case sensitive files is broken in default file storages

### ISSUE THREAD

**Issue by dahaupt** [IchHabRecht/filefill#18]
Enforcing a case sensitive file system introduced in 6757ce6  leads to an error while uploading files in case the toggle switch "Uses case sensitive identifiers" within an file storage is disabled.

Actually the file paths needs to become lowercase if the toggle switch is disabled. Else the file is "read-only" in file list, no thumbnail is generated and clicking the info button results in the exception:
```error
Object with identifier "1:/user_upload/My_LowerCased_File.jpg" does not exist in storage
```
Since I'm not sure why this change had to be made at all, a revert does not seem to be the best solution here. 

I would recommend to write a note in the "usage" section that this option has to be enabled in a file storage if it is also set in a file storage on a domain resource. Then the core function would not have to be overwritten and the extension would be compatible with the standard configuration of a FIle Storage.

**Comment by IchHabRecht** [comment]
Hi @dahaupt,

Thank you for your report. Unfortunately I'm unable to reproduce any error during the file upload in the filelist module. My setup:

TYPO3: 9.5
filefill: 3.0.1

I tested an upload of a lowercase and an uppercase file.

Would you mind to describe your setup a bit more? Do you use a case sensitive or insensitive filesystem on your test system?

The patch is necessary to not change any filename to lowercase, so an case sensitive production filesystem can be used even if the local one is insensitive. And if the local filesystem is case insensitive the file should be found with lower and upper cased filename.

**Comment by dahaupt** [comment]
Hello @IchHabRecht, thanks for your fast reply!

This is my setup:
TYPO3: **v9.5.14**
filefill: **v3.0.1**
DDEV: **v1.13.0** (running on Ubuntu 19.10)
File Storage database record: Uses case sensitive identifiers: **false**

After uploading some files it looks like this:
![image](https://user-images.githubusercontent.com/15915048/75249356-74a7e700-57d6-11ea-8232-18eef6736f62.png)

**Comment by IchHabRecht** [comment]
Hi @dahaupt,

Is there any way you can share your ddev installation? As I said, there cannot be any problem with uppercase filenames on an insensitive filesystem.

Can you check your user/group rights for your ddev installation? Why are those files read-only?

**Comment by IchHabRecht** [comment]
Hi @dahaupt,

Thank you for your further information. As we found out, you were using a case insensitive file storage on a case sensitive filesystem. This is not recommended at all and should be prevented.

To mitigate the problem I added a patch and released a new version of filefill that should not emit an error in your use case any more.
