### ISSUE TITLE
Not compatible with VHS ViewHelper "content.resources.fal"

### ISSUE THREAD

**Issue by baschny** [IchHabRecht/filefill#21]
At least for me it was not working. I have in the template:
```
<f:for each="{v:content.resources.fal(field: 'images')}" as="image">
```
This returns an empty array when the files are "absent" instead of having filefill fetch them. The culprid is this line in the ViewHelper:

https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Resource/Record/FalViewHelper.php#L234 : 
```
            if ($file->getProperty('t3ver_state') !== VersionState::DELETE_PLACEHOLDER) {
                try {
                    $resources[] = $this->arguments['asObjects'] ? $file : $this->getResource($file);
                } catch (\InvalidArgumentException $error) {
                    // Pokemon-style, catch-all and suppress. This exception type is thrown if a file gets removed.
                }
            }
```

Is there any way filefill can "hook into" earlier in the process so that the file "is there" for this ViewHelper to work? 

Or is this a bug in the way VHS uses the FAL API and I should file an issue on the VHS issue tracker?

**Comment by IchHabRecht** [comment]
Hi @baschny,

Thank you for your report. I had a look at the given viewhelper and have to admit, I fear I can't do very much. It seems the viewhelper returns an array of static file data as default without calling any FAL api that is handled by filefill. I'm unsure how I can help here, but will have another view soon.

**Comment by IchHabRecht** [comment]
Hi @baschny,

Would you mind to test the current master and check if #16 fixes your problem as well?

**Comment by baschny** [comment]
@IchHabRecht yes, indeed it works! Thanks a lot for the solution!

**Comment by IchHabRecht** [comment]
Then, I guess, this ticket can be closed as it's resolved ;-)
