### ISSUE TITLE
Incompatibility with TYPO3 v8 due to missing TYPO3\CMS\Core\Site\SiteFinder

### ISSUE THREAD

**Issue by julianhofmann** [IchHabRecht/filefill#24]
\IchHabRecht\Filefill\Repository\DomainResourceRepository uses TYPO3\CMS\Core\Site\SiteFinder which does not exist in TYPO3 v8. So the package could not be compatible with TYPO3 v8.7 anymore.

**Comment by IchHabRecht** [comment]
Hi @julianhofmann,

Thanks for your report. The SiteFinder is called only in versions of 9.5 and above. See https://github.com/IchHabRecht/filefill/blob/master/Classes/Repository/DomainResourceRepository.php

This is perfectly fine for TYPO3 8.7 as the class isn't used here.

**Comment by julianhofmann** [comment]
Theoretically, you're right.

But the version_compare() does not match because of wrong parameter order:
`version_compare(TYPO3_version, '<', '10')`

Should be:
>  `version_compare ( string $version1 , string $version2 , string $operator ) : bool`

**Comment by IchHabRecht** [comment]
Hi @julianhofmann,

That's a better report than the first one ;-) Thanks for your pull request.

**Comment by julianhofmann** [comment]
You're right. I had not analyzed the reason for the problem before you pointed out the version compare. Because I had the extension installed in a TYPO3 v8.7 and got an exception when running it, I took a deeper look.
