### ISSUE TITLE
Site Configuration

### ISSUE THREAD

**Issue by linawolf** [IchHabRecht/filefill#27]
as sys_domain is deprecated It would be great if Site Confiuration could be used.

**Comment by IchHabRecht** [comment]
Hi @linawolf,

Thank you for your ticket. Site configurations are already supported since version 3.2.0 (https://github.com/IchHabRecht/filefill/commit/c6c93fc7a5aa71e489bd4d14c854f137d7b398cd)

**Comment by linawolf** [comment]
Do we already have it in the documentation?

**Comment by IchHabRecht** [comment]
Hi @linawolf,

I'm not sure what your expectations are, so please feel free to submit any improvement.

**Comment by linawolf** [comment]
So the example in de Readme.md says:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']['storages'][1] = [
    [
        'identifier' => 'domain',
        'configuration' => 'https://example.com',
    ],
    [
        'identifier' => 'domain',
        'configuration' => 'https://another-example.com',
    ],
    [
        'identifier' => 'sys_domain',
    ],
    [
        'identifier' => 'placeholder',
    ],
];
```
Now how can I use the site_configuration instead of sys_domain?
will 
 [
        'identifier' => 'sys_domain',
    ],
just work with the site_configuration as well? Then I would put a sentence like sys_domain also works with site_config since version 3.2.0 ...

Is it another then i would put it in the example. Is there a list of all possible idenitifiers somewhere or just in the code?

**Comment by IchHabRecht** [comment]
Just use 'sys_domain' as it is only an identifier.

**Comment by linawolf** [comment]
I made a pull request to update the documentation:
https://github.com/IchHabRecht/filefill/pull/28

However i find it counter-intuitive that while site_configuration was introduce with TYPO3 9 (https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/SiteHandling/Index.html)

filefill does not repect it below Version 10  (see https://github.com/IchHabRecht/filefill/blob/3.x/Classes/Repository/DomainResourceRepository.php line 32) I would expect filefill to either respect both possible availible siteconfigurations and sys_domain entries or have it configureable ie one identifier for sys_domain and another for site_configuration.

**Comment by IchHabRecht** [comment]
Hi @linawolf,

To be honest I don't understand your remark. I'm trying hard to support as many TYPO3 versions as I can and filefill 3.x is compatible from TYPO3 8.7 to 10.4

**Comment by linawolf** [comment]
@IchHabRecht You are doing a great job, never wanted to question this. 

I am sorry if I misinterpreted the code, however in line 31 of DomainResourceRepository.php (https://github.com/IchHabRecht/filefill/blob/3.x/Classes/Repository/DomainResourceRepository.php)

is found the following:


```
        if (version_compare(TYPO3_version, '10', '<')) {
            return $this->findAllBySysDomainRecords();
        }

        return $this->findAllBySiteConfiguration();
```

So if the version is 9 findAllBySysDomainRecords() would be returned imidetly and findAllBySiteConfiguration() will never be called. Not sure if this is a bug or a missing feature. But to me using LTS 9 with filefill 3.2.0 the site configuration does not get considered.

After patching DomainResource Repository to change these lines to 

 ```
   public function findAll()
    {
        $domainResources = [];
        if (version_compare(TYPO3_version, '10', '<')) {
            $domainResources = $this->findAllBySysDomainRecords();
        }
        if (version_compare(TYPO3_version, '8', '>')) {
            $domainResources =  array_merge ($domainResources, $this->findAllBySiteConfiguration());
        }

        return $domainResources;
    }
```

it worked like charm for me.
You can find my patch attached:

[site_conf_lts9.zip](https://github.com/IchHabRecht/filefill/files/5177793/site_conf_lts9.zip)

**Comment by IchHabRecht** [comment]
Hi @linawolf,

I didn't remembered I implemented the site configuration that way. I took some time on the weekend and released a new filefill version that should solve your problem and support site configuration in TYPO3 9.5 as well.
Additionally I added a hint to the README file.

**Comment by linawolf** [comment]
Hi @IchHabRecht,

Wonderfull, thanks a lot!

Have a nice week!
