### ISSUE TITLE
Property "width" was not found in file reference or original file.

### ISSUE THREAD

**Issue by Rathch** [IchHabRecht/filefill#30]
The images that are downloaded, whether from the original website or from placeholder, have no width and height and cannot be edited in the fileadmin.

**Comment by IchHabRecht** [comment]
Hi @Rathch,

Please check the information in your exisiting meta data. If there isn't any height/width for a file filefill doesn't know about it.

**Comment by Rathch** [comment]
Hi @IchHabRecht You are right, in fact some files have a height and width 0 thanks

**Comment by IchHabRecht** [comment]
@Rathch Can this issue be closed then?

**Comment by Rathch** [comment]
yes
