### ISSUE TITLE
Deactivate per host without uninstalling

### ISSUE THREAD

**Issue by w010** [IchHabRecht/filefill#31]
Hello, your ext is very helpful in my everyday work, but currently I'm trying to make a setup in which it runs only on selected dev environments, while being basically inactive on production server, to avoid calling any unnecessary code there. But uninstalling ext there is not a solution, I need full git sync of whole system, so it must rely on configuration (or ApplicationContext) in fully automatic way. (so checkbox in storage record in database also won't help)
There is this option $GLOBALS['TYPO3_CONF_VARS']['EXT']['runtimeActivatedPackages'] which allows to enable extension conditionally, but, first thing, it doesn't keep database structure then, also this option is deprecated in 10.4.

My idea was to add something like that in ext_localconf:
```
call_user_func(function () {
	if ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']['deactivate'])   {
		return;
	}
....
```
which deactivates all hooks and slots registers, disables whole functionality while keeping extension installed, I can put global `'deactivate' => true` in LocalConfiguration and then set `'deactivate' => false` conditionally in AdditionalConfiguration.

But now I found version 4.0 which abandoned deprecated signal/slots for new yaml configured services as event listeners. And the whole idea is probably impossible to achieve with yaml (or at least I have no idea how to tell it to not load that yaml)
Do you have maybe any other idea how to do that? I didn't really want to put a number of conditions in every class just to tell it to exit. Maybe I forgot something simple or I can't just see an option for that.

**Comment by IchHabRecht** [comment]
Hi @w010,

If you have a composer installation you should require filefill in dev-context only. Other than that I don't see any solution to enable/disable an already installed extension in the TYPO3 eco system.

**Comment by w010** [comment]
That also won't work as expected, it will disable whole package and would ask to add/delete database columns on every db check when switching databases. So extension must be enabled always - but not doing anything on ApplicationContext == Production. Is that possible? Or do you use it in your projects on live servers?

**Comment by IchHabRecht** [comment]
I don't know anybody who use the extension on their live system. Me neither. If the extension isn't available on the live system there aren't any database fields, are there? You would deal with the database fields on your dev systems only.

**Comment by w010** [comment]
I need the database to be always 100% consistent with definitions from git-versioned source, when doing import/export of systems and automatic deploys. To not make any additional operations before local or remote use of a project. I need 100% full automatic solutions. If it'd be one project sometimes to work on, then ok, I can just install the ext. But I need to integrate such fetch mechanism as a standard steady solution into a few dozens of maintained projects in a number of stage environments, so I need this to be bulletproof to not have to think about it.
Ok, I'll try to figure that out somehow.

**Comment by kszymukowicz** [comment]
> Hi @w010,
> 
> If you have a composer installation you should require filefill in dev-context only. Other than that I don't see any solution to enable/disable an already installed extension in the TYPO3 eco system.

Activating in composer by installing in dev-context is ok for local instance but what with some staging instances where installing dev packages is not a good idea?

**Comment by schliesser** [comment]
@w010 You can configure it just for your Development/Staging instances with a condition around your configuration:

```php
if (TYPO3\CMS\Core\Core\Environment::getContext()->isDevelopment()) {
    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']['storages'][1] = [...];
}
```

**Comment by kszymukowicz** [comment]
@schliesser 

Your way is a good solution but the condition for checking if there is any config available should be earlier IMO.

Look here: https://github.com/IchHabRecht/filefill/blob/master/Classes/EventListener/ResourceStorageInitializationEventListener.php#L41

Before the condition to check for configuration there is at least few methods that looks like they are no not so CPU light. Maybe its good to first check if there is any configuration like `!empty($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']['storages'])` instead checking for specific configuration which can be done later.

This way it will be as light as possible.

**Comment by w010** [comment]
That's my point. I thought about this solution too, but it seems to check condition a bit too late, second thing is that occurs in more places - FileProcessing slot, ResourceFactory slot (and also formEngine.nodeRegistry, but ok, these are not that important)
So it would be perfect if that check runs as first thing in every key point - before doing anything else to minimalize its impact on performance and potential security (by the rule what doesn't run, is usually more secure)

**Comment by IchHabRecht** [comment]
Guys, all checks that are done are concerning to configuration. Please do not forget that configuration can be done on two ways for filefill: either in the storage record OR in global environments. I still recomment not to use filefill in any production environment. It is meant to be an extension helping to setup development system very easily. I guess we can close this ticket as the problem/question in this issue was solved already. Thanks for your understanding!

**Comment by kszymukowicz** [comment]
If you recommend to not use "filefill" in any production environment then it would be nice to maybe update documentation with statement that this extension is not supposed to be installed on any staging and production instances.

Also maybe good to change the doc part:

"Simply install the extension with Composer or the Extension Manager.
composer require ichhabrecht/filefill"

to

"Simply install the extension with Composer or the Extension Manager.
composer require --dev ichhabrecht/filefill"

Tnx.

**Comment by w010** [comment]
Will you merge if I do that?

**Comment by IchHabRecht** [comment]
To be honest I do believe every developer should be able to decide whether an extension is required on a system or not. As I told, I think it's not necessary to install it on a productive system. But it might be required on a staging system to ensure all files available. So i would not just recommend to install it on dev systems only, but install the extension where needed. I truly think this issue described in this ticket is a very special one. So to be honest I don't see any reason to change the README file.

**Comment by w010** [comment]
I think having PackageStates.php versioned, consistent between dev/stage/master branches, and autodeployed to corresponding server on push is not a special case at all, rather standard automatized workflow in business. Modifying extensions list manually on one target environment to have a functionality on demand, just to have the PackageStates suddenly restored to previous state when someone pushes to git, is really not a serious option.
