### ISSUE TITLE
Unexpected File Fill Resource configuration "1"

### ISSUE THREAD

**Issue by Gernott** [IchHabRecht/filefill#34]
This error appears in TYPO3 9.5.24 with filefill 2.0.3 in composer mode, when setting the configuration via PHP/AdditionalConfiguration.php (copy&paste from the Manual).
As workaround, I can store the configuration in the Database.
Any hints what's wrong?
![Bildschirmfoto von 2021-02-16 13-39-51](https://user-images.githubusercontent.com/1930849/108064204-a0158880-705c-11eb-8697-83d653ab4958.png)

**Comment by IchHabRecht** [comment]
Hi @Gernott,

Would you mind to share your configuration and re-check if it is the correct one for the 2.x version?

**Comment by Gernott** [comment]
Thank you for your reply. Oh, has it changed? Where can I find the old one? Then I can try it directly.

**Comment by IchHabRecht** [comment]
Hi @Gernott,

You should have the old README.md within your installation ;-)

**Comment by Gernott** [comment]
Ha, so easy. Of course.
I think that's it. I try this later and close this issue when confirmed.

**Comment by IchHabRecht** [comment]
@Gernott you may should consider to update to the latest 3.x version!

**Comment by Gernott** [comment]
Yes, I'm currently wondering why I have v2 installed.

**Comment by Gernott** [comment]
Update to v3 resolves it. Sorry for this.
