### ISSUE TITLE
How are processed images handled?

### ISSUE THREAD

**Issue by dr2okevin** [IchHabRecht/filefill#35]
More a question than an issue. But how are processed images hanled? I have seen that they won't be downloaded if the original file exists, and they are marked as processed in the DB. But what happens if the original file don't exist. Will the original file downloaded, or the processed or nothing?

**Comment by IchHabRecht** [comment]
Hi @dr2okevin,

First the original file is tried to be downloaded but if this file doesn't exists remotely the processed one is tried as well. Hope this answers your question. If you have any problems don't hesitate to give some more information about your problem and use case.

**Comment by jackd248** [comment]
Hej @IchHabRecht,
we got the problem, that the downloaded original images are quite large, so the following downsizing/processing image process of the retrieved images are very performance heavy. Is it possible to force the download of the processed images? Or force the download of both, original and processed? 
Thanks so far, keep up the good work

**Comment by jackd248** [comment]
Thanks for the fast reply, I will have a look on this option.
