### ISSUE TITLE
TYPO3_CONF_VARS configuration not resolved

### ISSUE THREAD

**Issue by jokumer** [IchHabRecht/filefill#37]
Hello Nicole,

### Given

* TYPO3 version 10.4 with TYPO3_CONF_VARS configuration for one single file storage
* Configured like described in README.md (added to AdditionalConfig.php)
* Using 'domain' as identifier
* No further DB:sys_file_storage record configuration

### Expected

* Fetching assets from given domain through TYPO3_CONF_VARS configuration like it does with comparable Database record configuration

### Actual

* Assets does **NOT** load with TYPO3_CONF_VARS configuration
* Assets does load with comparable Database record configuration

### Solution

Fix use of `createRemoteResourceCollectionFromConfiguration` in `ResourceFactorySlot->initializeResourceStorage`.
Patch pending.

**Comment by jokumer** [comment]
Version 3.3.1

**Comment by IchHabRecht** [comment]
Hi @jokumer,

As I can't find any pending patch, would you mind to share your configuration?

**Comment by jokumer** [comment]
```
$GLOBALS['TYPO3_CONF_VARS'] = array_replace_recursive(
	$GLOBALS['TYPO3_CONF_VARS'],
	[
		'DB' => [...],
		'GFX' => [...],
		'MAIL' => [...],
		'SYS' => [...],
		'EXTCONF' => [
			'filefill' => [
				'storages' => [
					6 => [
						'identifier' => 'domain',
						'configuration' => 'https://www.domain.tld',
					]
				]
			]
		]
	]
);
```
<img width="571" alt="issue37-config" src="https://user-images.githubusercontent.com/6431813/122365774-4023e580-cf5b-11eb-900b-99ac1de634db.png">

**Comment by IchHabRecht** [comment]
Hi @jokumer,

Would you mind to use the correct configuration according to the documentation https://github.com/IchHabRecht/filefill/blob/3.x/README.md#typo3_conf_vars-configuration ;-) You need to wrap the configuration/identifier array in a global array.

**Comment by jokumer** [comment]
Ah, now i see my fault. Thx and sorry for disturb.
