### ISSUE TITLE
Add support for video files: .youtube and .vimeo

### ISSUE THREAD

**Issue by kitzberger** [IchHabRecht/filefill#47]

**Comment by IchHabRecht** [comment]
Hi  @kitzberger,

Thank you for your report. I just set up a test scenario on my dev system. Everything is working as expected for missing video/media files. Those files are already fetched properly from defined remote resources (using 'domain' or 'sys_domain' identifiers).

**Comment by kitzberger** [comment]
Sure, that's true! But in my case there's no remote system to fetch resources from. Hence the ascii handler. But OK, we'll run with our fork of your extension then ;-)

**Comment by ayacoo** [comment]
Hi, I'm running into this problem right now too. Do you have any idea how we can document this and what the specific questions would be? It is also the case with me that no remote system is used.

My question right now is: What would I need to set up to get online providers like Youtube/Vimeo/etc. working?

I would also offer a PR, am just undecided what is now the "official" way :-)

**Comment by ayacoo** [comment]
@IchHabRecht Okay, if I understand it correctly you would leave out the AsciiHandler from the PR as well, right? At least that's what the closed pull request implies ;-)

Then my suggestion would be that under "Known issues" we mention the textfile handling including Youtube once and then refer to the resource handler place in the doc. Would that be ok?

**Comment by IchHabRecht** [comment]
@ayacoo I still don't get your expectation yet

**Comment by ayacoo** [comment]
@IchHabRecht Okay, I try again :-)

Context: TYPO3 migration and no connection to a remote system.  EXT:filefill is initialized with placeholder.com, so for images it works. When I call the page I get this error message.

PHP Warning: file_get_contents(/var/www/html/public/fileadmin/user_upload/[CUSTOM_FILENAME].youtube): failed to open stream:

What I'm missing now is any info on how to handle it as a newbie. 

Variant A: Is apparently this pull request, which would integrate its own handling
Variant B: Maybe extend the documentation a bit to write this case. "Dear user: In case of Youtube/Vimeo videos and without remote system, please build a resource handler. You can find an example here:" Link to pull request or a simple example in the Readme file. For me, the connection between Additional resources and Youtube was not clear here.

I hope my request became a little clearer :-)

**Comment by kitzberger** [comment]
@IchHabRecht, give the people what they want ;-)  No, seriously, it's a plain and simple change that could cover a lot of use cases. Just saying ;-)

**Comment by IchHabRecht** [comment]
@kitzberger I have concept for a more generic solution to cover all other files as well. Currently looking for some sponsoring to implement it. But as I already tried to explain, I don't think it is a common use case (for filefill) to set it up without any remote at all. This was never a concept I wanted to support. BTW: not all of us understand that kind of joke!

**Comment by ayacoo** [comment]
For me that's okay, because you are the owner of the extension and you have to make the decisions. I will orient myself for my case on the basis of the PR and if someone is still looking for it, there are enough tips here how to deal with the case.

**Comment by IchHabRecht** [comment]
Hi @kitzberger @ayacoo 
It would be really cool if you could test the attached merge request and give me some feedback if this is a proper way to solve your requirements.

**Comment by kitzberger** [comment]
@IchHabRecht, cool, solid feature I'd say ;-) Thanks a lot!
