### ISSUE TITLE
Unable to send test email from install tool due to exception of ext:filefill

### ISSUE THREAD

**Issue by derhansen** [IchHabRecht/filefill#55]
With version 4.0.1 of the extension, it is no longer possible for me to send a test mail from the install tool. Sending fails with the following exception created by ext:filefill

```
Please verify $GLOBALS['TYPO3_CONF_VARS']['MAIL'][*] settings are valid. Error message: Unexpected File Fill Resource configuration "domain"
```

The Exception is thrown in `RemoteResourceCollectionFactory::createRemoteResourceCollectionFromFlexForm()`, where `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['filefill']` is empty.

![image](https://user-images.githubusercontent.com/2629896/160794133-6590f1b3-d6d8-4e1e-a0a0-dd995441c0ed.png)

Environment: TYPO3 version 10.4, non composer setup, PHP 7.4

Downgrading to version 3.3.1 resolves the problem.

**Comment by IchHabRecht** [comment]
Hi @derhansen,

proper configuration for filefills handler is provided in ext_localconf.php and should be available by default. Would you mind to check where this configuration might get lost?

**Comment by derhansen** [comment]
Hi @IchHabRecht,

I debugged this and came to the conclusion, that this may be a bug in TYPO3 core. On the first request to the "Environment" backend module, `typo3/index.php` is called and starts the TYPO3 bootstrap process. After that, `typo3/install.php` is called, which again initializes the TYPO3 bootstrap process, but in non-cached mode (argument `$failsafe` is `false`). If this is the case, the configuration of extensions is not loaded (https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Core/Bootstrap.php#L151 - we never reach line 158 with `static::loadTypo3LoadedExtAndExtLocalconf(true, $coreCache);` at this point). Unsure if this is a bug or expected behavior, but usually the TYPO3 install tool does not need to initialize extension configuration from `ext_localconf.php`, su I guess this works as intended.

The reported problem does however only occur, when either a custom backend login logo (`login.loginLogo`) or a custom highlight color (`login.loginHighlightColor`) is configured for ext:backend. If one of both cases match, the `AfterResourceStorageInitializationEvent` PSR-14 event is called, because TYPO3 uses FAL to access images used in `FluidEmail`. ext:filefill listens to that event and tries to access `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']`, which does not exist, because TYPO3 did not initialize extension configuration in install tool context.

Hard to debug and for sure an edge case, which IMO does not require more attention or work. The issue is filed here so other users experiencing the same error can find a proper workaround to avoid the problem (do not use `login.loginLogo` and `login.loginHighlightColor` when using ext:filefill). I'm closing the issue now.
