### ISSUE TITLE
Support for TYPO3v12 LTS

### ISSUE THREAD

**Issue by mbrodala** [IchHabRecht/filefill#70]
Currently only TYPO3v12 12.0.x/12.1.x is supported by this package. Support for the final LTS (12.4.x) should be added/declared.

**Comment by patriciaschierling** [comment]
Are there any news on the timing for the implementation?

**Comment by IchHabRecht** [comment]
@patriciaschierling As soon as I find some spare time I can care about the extension maintenance.

**Comment by IchHabRecht** [comment]
Resolved with the release of filefill 4.3.0

**Comment by mbrodala** [comment]
Thanks a lot for taking care. :-)
