### ISSUE TITLE
Cannot add file while using FileFillDriver, 

### ISSUE THREAD

**Issue by alkapone312** [IchHabRecht/filefill#84]
Description:
While adding file TYPO3\CMS\Core\Resource\ResourceStorage uses function fileExists(), filefill driver overwrites methods with code linked below

https://github.com/IchHabRecht/filefill/blob/be12bf32e5448c6482d4d2ea265394dbc814d939/Classes/Resource/Driver/FileFillDriver.php#L171

Issue:
When adding file, it does not exists, getPublicUrl now can return NULL, but remoteResourceCollection requires filePath to be not null as described in interface, which throws an exception. Same happens while invoking
TYPO3\CMS\Core\Resource\ResourceStorage::hasFileInFolder

**Comment by IchHabRecht** [comment]
Hi @alkapone312 

Thank you for submitting this issue. Would you mind to add the steps I need to do to be able to reprocude this error?

**Comment by alkapone312** [comment]
Sorry, I've made too fast assumption, the only issue I see on your side is that you provide possibly null value as a parameter to function that in phpdoc assures string, the issue were in another plugin where the value was provided to method with string typed in php that caused type error

**Comment by IchHabRecht** [comment]
Hi @alkapone312 

would you mind to explain which function returns null to a function that needs a string as input?

**Comment by IchHabRecht** [comment]
Furthermore the PHPDoc comments aren't parsed in any way. So even if the filePath should become NULL, the would code still work.

**Comment by alkapone312** [comment]
Just because they aren't parsed doesn't mean they should be ignored. They are part of documentation and here code and docs states differently. However I don't care, issue is not on your site so this topic can be closed. Sorry for taking up your time.
